describe('types', () => {
  require('./Array')
  require('./ArrayExtension')
  require('./Boolean')
  require('./BooleanExtension')
  require('./Date')
  require('./DateExtension')
  require('./Number')
  require('./NumberExtension')
  require('./Object')
  require('./ObjectExtension')
  require('./String')
  require('./StringExtension')
})
